//Action Types Constants

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'

export const USER_ACCESS = 'USER_ACCESS'
export const CLEAR_USER_ACCESS = 'CLEAR_USER_ACCESS'

export const GET_USER_REPORTS = 'GET_USER_REPORTS'
export const CLEAR_USER_REPORTS = 'CLEAR_USER_REPORTS'

export const SELECT_COMPANY = 'SELECT_COMPANY'
export const SELECT_PARKING = 'SELECT_PARKING'
export const SELECT_PARKINGLOT = 'SELECT_PARKINGLOT'
export const SELECT_USER = 'SELECT_USER'
export const CLEAR_SELECT = 'CLEAR_SELECT'
